
server:
  port: 8088
  servlet:
    session:
      tracking-modes: cookie
spring:
  datasource:
    url: jdbc:mysql://redhome.ci6s4nlbxagk.ap-northeast-2.rds.amazonaws.com:3306/CPRPROJECT
    username: CPRPROJECT
    password: CPRPROJECT
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

  servlet:
    multipart:
      enabled: true   # 파일 업로드 가능 여부 선택
      max-request-size: 30MB    # 한번에 최대 업로드 가능 용량
      max-file-size: 10MB        # 파일 하나의 초대 크기

  messages:
    basename: i18n/messages
    encoding: UTF-8

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.CPR.redHome.dto.**.*
